service: delfosti-backend-card-tokenization
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  environment:
    REDIS_URL: 'redis://:root@127.0.0.1:6379/0'

functions:
  health:
    handler: src/functions/health/index.handler
    events:
      - httpApi:
          path: /health
          method: get
  createToken:
    handler: src/functions/tokenization/index.handler
    events:
      - httpApi:
          path: /create-token
          method: post
  getCardInformation:
    handler: src/functions/card-information/index.handler
    events:
      - httpApi:
          path: /card-information/{token}
          method: get

resources:
  Resources:
    Personas:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Card
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

plugins:
  - serverless-plugin-typescript
  - serverless-offline

