export const eventRequestMock: any = {
  body: null,
  cookies: [],
  headers: {
    host: 'localhost:3000',
    'content-type': 'application/json',
    'user-agent': 'insomnia/8.6.0',
    authorization: 'pk_test_BuyK6NguwyPEuD33',
    accept: '*/*',
    'content-length': '146',
  },
  isBase64Encoded: false,
  pathParameters: { token: 'i1dAUiRS9Yega0iQ' },
  queryStringParameters: null,
  rawPath: '/card-information/i1dAUiRS9Yega0iQ',
  rawQueryString: '',
  requestContext: {
    accountId: 'offlineContext_accountId',
    apiId: 'offlineContext_apiId',
    authorizer: { lambda: {}, jwt: [Object] },
    domainName: 'offlineContext_domainName',
    domainPrefix: 'offlineContext_domainPrefix',
    requestId: 'offlineContext_resourceId',
    routeKey: 'GET /card-information/{token}',
    stage: '$default',
    protocol: 'http',
    httpMethod: 'GET',

    path: 'PATH',
    requestTimeEpoch: 10,
    resourceId: 'id',
  },
  routeKey: 'GET /card-information/{token}',
  stageVariables: null,
  version: '2.0',
};
